#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular-FileUpload
Version  : 12.0.4.0
Release  : 15
URL      : https://files.pythonhosted.org/packages/4d/fd/c3051915d2f12e8fa11f59c01162ce85e38eca15d9ec73a3d7b271b49744/XStatic-Angular-FileUpload-12.0.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/4d/fd/c3051915d2f12e8fa11f59c01162ce85e38eca15d9ec73a3d7b271b49744/XStatic-Angular-FileUpload-12.0.4.0.tar.gz
Summary  : Angular-FileUpload 12.0.4 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-Angular-FileUpload-python = %{version}-%{release}
Requires: XStatic-Angular-FileUpload-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
-------------------------
        
        Angular-FileUpload JavaScript library packaged for setuptools (easy_install) / pip.
        
        This package is intended to be used by **any** project that needs these files.
        
        It intentionally does **not** provide any extra code except some metadata
        **nor** has any extra requirements. You MAY use some minimal support code from
        the XStatic base package, if you like.
        
        You can find more info about the xstatic packaging way in the package `XStatic`.

%package python
Summary: python components for the XStatic-Angular-FileUpload package.
Group: Default
Requires: XStatic-Angular-FileUpload-python3 = %{version}-%{release}
Provides: xstatic-angular-fileupload-python

%description python
python components for the XStatic-Angular-FileUpload package.


%package python3
Summary: python3 components for the XStatic-Angular-FileUpload package.
Group: Default
Requires: python3-core
Provides: pypi(xstatic_angular_fileupload)

%description python3
python3 components for the XStatic-Angular-FileUpload package.


%prep
%setup -q -n XStatic-Angular-FileUpload-12.0.4.0
cd %{_builddir}/XStatic-Angular-FileUpload-12.0.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583702690
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
